# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.BooleanField()),
                ('mobile', models.BooleanField()),
                ('other_type', models.BooleanField()),
                ('specify_other_type', models.CharField(max_length=800)),
                ('fe', models.BooleanField()),
                ('be', models.BooleanField()),
                ('full_stack', models.BooleanField()),
                ('linkedin', models.BooleanField()),
                ('linkedin_link', models.URLField(blank=True, default='')),
                ('github', models.BooleanField()),
                ('github_link', models.URLField(blank=True, default='')),
                ('website', models.BooleanField()),
                ('website_link', models.URLField(blank=True, default='')),
                ('other_profile', models.BooleanField()),
                ('specify_other_profile', models.URLField(blank=True, default='')),
                ('dev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dev', models.BooleanField()),
                ('simple_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
